In [3]:
import numpy as np

In [4]:
aliste = [1,2,3,4]
a = np.array(aliste)
b = np.array([2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [10]:
np.array([3.14, 4.05, 2.6, 13.75], dtype = "int")

array([ 3,  4,  2, 13])

In [9]:
np.array([3.14, 4.05, 2.6, 13.75], dtype = "float")

array([ 3.14,  4.05,  2.6 , 13.75])

In [11]:
# sifir array olusturma
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# birlerden olusan 3x5 lik bir array olusturma
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# sonunda 3 yazıldıgında 3x5'lik 3'lerden olusana bır array  
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [14]:
# 0-31 arasından ikişerli ikişerli bır array olusturur
np.arange(0,31,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [16]:
# np.linspace(start, stop, num)
# start: Oluşturulan aralığın başlangıç değeri.
# stop: Oluşturulan aralığın bitiş değeri.
# num: Oluşturulan eşit aralıklı değerlerin sayısı.

np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [17]:
# np.random.normal(mean, std_deviation, size)
# mean: Normal dağılımdaki ortalamayı belirler.
# std_deviation: Normal dağılımdaki standart sapmayı belirler.
# size: Üretilecek rastgele sayıların şeklini (boyutunu) belirler.

np.random.normal(10, 3, (3,4))

array([[ 8.10979551,  9.67752627, 10.90094374, 14.88356472],
       [11.58130389,  4.63574746, 12.17098459,  6.19772249],
       [ 4.56161868,  6.60116234,  9.48872968, 10.98384074]])

In [7]:
# np.random.randint(low, high, size)
# low: Oluşturulan aralığın alt sınırı (dahil).
# high: Oluşturulan aralığın üst sınırı (hariç).
# size: Oluşturulan rastgele değerlerin şeklini (boyutunu) belirler.
b=np.random.randint(0,10, (3,3))

In [11]:
#.ndim (boyut sayısı) gösterir.
print( "b.ndim=",b.ndim)
print("b.shape=",b.shape)
print("b.size=",b.size)
print("b.dtype=",b.dtype)

b.ndim= 2
b.shape= (3, 3)
b.size= 9
b.dtype= int32


# Yeniden Şekillendirme (Reshaping)

In [14]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# np.arange(start, stop)
# start: Dizinin başlangıç değeri.
# stop: Dizinin bitiş değeri (hariç).

# np.reshape((rows, cols))
# rows: Matrisin satır sayısı.
# cols: Matrisin sütun sayısı.

np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:

# np.arange(start, stop)
# start: Dizinin başlangıç değeri.
# stop: Dizinin bitiş değeri (hariç).

a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [23]:
# np.concatenate(arrays, axis)
# arrays: Birleştirilecek dizileri içeren bir liste veya demet.
# axis: Birleştirme işleminin yapılacağı eksen. Varsayılan değeri 0'dır (satır bazında birleştirme).

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
# y dizisinin transpozu (T):

np.concatenate([x, y.T], axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [25]:
# np.concatenate([a, a]) ile matris a, kendisi ile satır bazında birleştirilir:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
# np.concatenate([a, a], axis=1) ile matris a, kendisi ile sütun bazında birleştirilir:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [27]:
import numpy as np
x = np.array([1,2,3,99,99,3,2,1])

In [29]:
# np.split(x, [3, 5]) ile diziyi indeks 3 ve 5'te böler:
# [array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [70]:
a,b,c = np.split(x, [3,5])
print("a:  {} b: {} c: {}  ".format(a,b,c))


a:  [1 2 3] b: [99 99] c: [3 2 1]  


In [31]:
#iki boyutlu ayırma
# np.vsplit(m, [2]) ile matris m, 2. satırda dikey olarak böler:
m = np.arange(16).reshape(4,4)
np.vsplit(m, [2])


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [68]:
ust, alt = np.vsplit(m, [2])
print("ust: \n {} \n alt:\n {}".format(ust,alt))

ust: 
 [[2 7 1 3 5]
 [6 0 8 3 8]] 
 alt:
 [[3 0 6 0 2]]


In [40]:
# np.hsplit(m, [2]) ile matris m, 2. sütündan yatay olarak böler:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [65]:
sag, sol = np.hsplit(m, [2])
print("sag: \n {} \n sol:\n {}".format(sag,sol))


sag: 
 [[2 7]
 [6 0]
 [3 0]]
 sol:
 [[1 3 5]
 [8 3 8]
 [6 0 2]]


# Array Sıralama (Sorting)

In [45]:
import numpy as np
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [46]:
# v.sort() ile dizi v sıralanır:
v.sort()
v


array([1, 2, 3, 4, 5])

In [48]:
# np.random.normal(loc, scale, size)
# loc: Ortalama değer (dağılımın merkezi).
# scale: Standart sapma (dağılımın genişliği).
# size: Oluşturulacak dizi boyutu.

# np.random.normal(20, 5, (3, 3)) ifadesi ile normal dağılıma sahip rastgele sayılardan oluşan 3x3 matris oluşturulur.
m = np.random.normal(20, 5, (3, 3))

# np.sort(m, axis=1) ile matris m, satır bazında (yatayda) sıralanır:

sorted_m = np.sort(m, axis=1)
sorted_m

array([[21.09644664, 25.9999048 , 31.03785621],
       [11.58094349, 18.54776548, 21.95068532],
       [13.5127138 , 24.10246072, 28.85881894]])

In [49]:
# np.sort(m, axis=0) ile matris m, sütun bazında sıralanır:
sorted_m = np.sort(m, axis=0)
sorted_m

array([[21.09644664, 11.58094349, 18.54776548],
       [21.95068532, 13.5127138 , 24.10246072],
       [28.85881894, 25.9999048 , 31.03785621]])

# Index ile Elemanlara Erişmek

In [52]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([7, 9, 2, 8, 0, 8, 9, 6, 7, 3])

In [55]:
print(a[0],a[-1])
a[1] = 100
print(a)

7 3
[  7 100   2   8   0   8   9   6   7   3]


In [61]:
m = np.random.randint(10, size = (3,5))
print("m[0,0]= {} m[1,1]= {} m[1, 4]= {}  ".format(m[0,0], m[1,1],m[1, 4]))



m[0,0]= 2 m[1,1]= 0 m[1, 4]= 8  


In [58]:
m[1, 4] = 99
m 

array([[ 4,  4,  7,  9,  3],
       [ 4,  8,  5,  3, 99],
       [ 9,  4,  4,  3,  5]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [60]:
import numpy as np
a = np.arange(20,30)


print("a= {} a[0:3]= {} a[:3]= {} a[3:]= {} ".format(a, a[0:3],a[:3],a[3:]))

a= [20 21 22 23 24 25 26 27 28 29] a[0:3]= [20 21 22] a[:3]= [20 21 22] a[3:]= [23 24 25 26 27 28 29] 


In [92]:
# np.random.randint(10, size=(5, 5)) ifadesi ile 0 ile 9 arasında rastgele sayılardan oluşan 5x5 boyutunda bir matris oluşturulur.

m = np.random.randint(10, size = (5,5))

# "m[:, 0] {} m[0:5, 1] {} m[:, 4] {}." ifadesi ile m matrisinin belirli satır ve sütunlarının değerleri birleştirilerek yazdırılır.

# m[:, 0]: Matris m'nin tüm satırlarını ve 0. sütununu seçer.
# m[0:5, 1]: Matris m'nin 0'dan 4'e kadar olan satırlarını (5. satır hariç) ve 1. sütununu seçer.
# m[:, 4]: Matris m'nin tüm satırlarını ve 4. sütununu seçer.

print(" m[:,0]= {} \n\n m[0:5,1])= {} \n\n m[:,4])= {} \n\n m: \n {} \n\n m[0,:]= {} \n\n m[0]= {} \n\n m[1,:]= {} \n\n m[0:2, 0:3]: \n {} \n m[:,0:2]: \n {} \n m[1:3, 0:2]: \n {} ".format(m[:,0], m[0:5,1],m[:,4],m,m[0,:],m[0],m[1,:],m[0:2, 0:3],m[:,0:2],m[1:3, 0:2]  ))


 m[:,0]= [5 1 2 0 8] 

 m[0:5,1])= [5 2 5 5 6] 

 m[:,4])= [8 0 3 3 3] 

 m: 
 [[5 5 6 4 8]
 [1 2 4 0 0]
 [2 5 1 4 3]
 [0 5 8 5 3]
 [8 6 7 5 3]] 

 m[0,:]= [5 5 6 4 8] 

 m[0]= [5 5 6 4 8] 

 m[1,:]= [1 2 4 0 0] 

 m[0:2, 0:3]: 
 [[5 5 6]
 [1 2 4]] 
 m[:,0:2]: 
 [[5 5]
 [1 2]
 [2 5]
 [0 5]
 [8 6]] 
 m[1:3, 0:2]: 
 [[1 2]
 [2 5]] 


# Alt Küme Üzerinde İşlem Yapmak

In [93]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[0, 9, 8, 4, 2],
       [2, 4, 5, 3, 9],
       [5, 6, 1, 0, 1],
       [8, 4, 6, 8, 8],
       [7, 2, 2, 5, 9]])

In [95]:
alt_a = a[0:3, 0:2]
print(" alt_a: \n {} ".format(alt_a))


 alt_a: 
 [[0 9]
 [2 4]
 [5 6]] 


In [97]:
alt_a[0,0] = 99999
alt_a[1,1] = 888
print(" alt_a: \n {} ".format(alt_a))

 alt_a: 
 [[99999     9]
 [    2   888]
 [    5     6]] 


In [98]:
print(" a: \n {} ".format(a))

 a: 
 [[99999     9     8     4     2]
 [    2   888     5     3     9]
 [    5     6     1     0     1]
 [    8     4     6     8     8]
 [    7     2     2     5     9]] 


In [100]:
m = np.random.randint(10, size = (5, 5))
alt_b = m[0:3, 0:2].copy()
alt_b[0,0] = 9999

print(" alt_b: \n {} \n m: \n {} ".format(alt_b,m))




 alt_b: 
 [[9999    3]
 [   9    4]
 [   5    7]] 
 m: 
 [[2 3 0 3 2]
 [9 4 6 9 5]
 [5 7 5 4 3]
 [7 3 2 1 4]
 [2 0 1 4 0]] 


# Fancy Index ile Elemanlara Erişmek

In [104]:
import numpy as np
v = np.arange(0, 30, 3)
print(" v: {} \n v[1]: {} v[3]: {} v[5]: {} [v[1], v[3], v[5]]: {}  ".format(v,v[1],v[3],v[5],[v[1], v[3], v[5]]))

 v: [ 0  3  6  9 12 15 18 21 24 27] 
 v[1]: 3 v[3]: 9 v[5]: 15 [v[1], v[3], v[5]]: [3, 9, 15]  


In [105]:
al_getir = [1,3,5]
print("v[al_getir]: {}".format(v[al_getir]))


v[al_getir]: [ 3  9 15]


In [110]:
m = np.arange(9).reshape((3,3))
satir = np.array([0,1])
sutun = np.array([1,2])
print(" m:\n {} \n m[satir, sutun]: {}".format(m,m[satir, sutun]))

 m:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
 m[satir, sutun]: [1 5]


In [127]:
#basit index ile fancy index
    
m = np.arange(9).reshape((3,3))
print(" m[0, [1,2]]:  {} \n m[0:, [1,2]]: \n {} ".format(m[0 , [1,2]],m[0:, [1,2]] ))



 m[0, [1,2]]:  [1 2] 
 m[0:, [1,2]]: 
 [[1 2]
 [4 5]
 [7 8]] 


# Koşullu Eleman İşlemleri

In [9]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [10]:
print(" v < 3: {} \n v[v < 3]: {} \n v[v > 3]: {} \n v[v >= 3]: {} \n v[v <= 3]: {} \n v[v == 3]: {}  \n v[v != 3]: {} ".format(v < 3,v[v < 3],v[v > 3],v[v >= 3],v[v <= 3],v[v == 3],v[v != 3] ))

 v < 3: [ True  True False False False] 
 v[v < 3]: [1 2] 
 v[v > 3]: [4 5] 
 v[v >= 3]: [3 4 5] 
 v[v <= 3]: [1 2 3] 
 v[v == 3]: [3]  
 v[v != 3]: [1 2 4 5] 


In [11]:
print("v: {} \n v*2: {} \n v / 5: {} \n v*5/10: {} \n v**2: {} ".format(v, v*2, v / 5, v*5/10, v**2 ) )

v: [1 2 3 4 5] 
 v*2: [ 2  4  6  8 10] 
 v / 5: [0.2 0.4 0.6 0.8 1. ] 
 v*5/10: [0.5 1.  1.5 2.  2.5] 
 v**2: [ 1  4  9 16 25] 


# Matematiksel İşlemler

In [30]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [31]:
print(" v - 1: {} \n v * 5: {} \n v / 5: {} \n v*5/10 - 1: {} \n v-1*2: {}  ".format(v - 1,v * 5,v / 5,v*5/10 - 1,v-1*2))

 v - 1: [0 1 2 3 4] 
 v * 5: [ 5 10 15 20 25] 
 v / 5: [0.2 0.4 0.6 0.8 1. ] 
 v*5/10 - 1: [-0.5  0.   0.5  1.   1.5] 
 v-1*2: [-1  0  1  2  3]  


In [41]:
# np.subtract(v, 1) ifadesi ile v dizisindeki her bir elemandan 1 çıkarılır:
subtract = np.subtract(v, 1)# np.add(v, 1) ifadesi ile v dizisindeki her bir elemana 1 eklenir:
add = np.add(v, 1)
# np.multiply(v, 4) ifadesi ile v dizisindeki her bir eleman 4 ile çarpılır:
multiply = np.multiply(v,4)
# np.divide(v, 3) ifadesi ile v dizisindeki her bir eleman 3'e bölünür:
divide = np.divide(v, 3)
# np.power(v, 3) ifadesi ile v dizisindeki her bir elemanın 3. kuvveti alınır:
power = np.power(v, 3)
# np.mod(v, 2) ifadesi ile v dizisindeki her bir elemanın 2'ye göre modu (kalanı) alınır:
mod = np.mod(v, 2)
# np.array([-3]) ifadesi ile [-3] elemanından oluşan bir Numpy dizisi oluşturulur.
# -3 sayısı tek elemanlı bir dizi içindedir.
# np.absolute(np.array([-3])) ifadesi ile bu dizinin mutlak değeri alınır:
absolute = np.absolute(np.array([-3]))

print(" subtract: {}\n add: {} \n multiply: {} \n divide: {} \n power: {} \n mod: {} \n absolute: {}".format(subtract,add,multiply,divide,power,mod,absolute))


 subtract: [0 1 2 3 4]
 add: [2 3 4 5 6] 
 multiply: [ 4  8 12 16 20] 
 divide: [0.33333333 0.66666667 1.         1.33333333 1.66666667] 
 power: [  1   8  27  64 125] 
 mod: [1 0 1 0 1] 
 absolute: [3]


In [42]:
print(" v**2: {} \n v**3: {} \n v % 2: {} ".format(v**2,v**3,v % 2,))

 v**2: [ 1  4  9 16 25] 
 v**3: [  1   8  27  64 125] 
 v % 2: [1 0 1 0 1] 


In [43]:
# np.sin(360) ifadesi ile 360 derecelik açının sinüsü hesaplanır:
sin_value = np.sin(360)
# np.cos(180) ifadesi ile 180 derecelik açının kosinüsü hesaplanır:
cos_value = np.cos(180)

print(" sin_value: {} \n cos_value: {} ".format(sin_value,cos_value))



 sin_value: 0.9589157234143065 
 cos_value: -0.5984600690578581 


In [47]:
v = np.array([1,2,3])
# np.log(v) ifadesi ile v dizisindeki her bir elemanın doğal logaritması alınır:
log_value = np.log(v)
# np.log2(v) ifadesi ile v dizisindeki her bir elemanın taban 2 logaritması alınır:
log2_value = np.log2(v)
# np.log10(v) ifadesi ile v dizisindeki her bir elemanın taban 10 logaritması alınır:
log10_value = np.log10(v)
print(" log:  {} \n log2  {} \n log10:  {} ".format(log_value,log2_value,log10_value))



 log:  [0.         0.69314718 1.09861229] 
 log2  [0.        1.        1.5849625] 
 log10:  [0.         0.30103    0.47712125] 


# İstatistiksel Hesaplamalar

In [4]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

# "v" adında bir NumPy dizisi oluşturuyoruz. Bu dizi [1, 2, 3, 4, 5] değerlerini içeriyor.
mean_v = np.mean(v)
# "np.mean()" fonksiyonu, "v" dizisinin ortalamasını hesaplar ve "mean_v" değişkenine atar.
sum_v = v.sum()
# "sum()" metodu, "v" dizisindeki tüm elemanların toplamını hesaplar ve "sum_v" değişkenine atar.
min_v = v.min()
# "min()" metodu, "v" dizisindeki en küçük elemanı bulur ve "min_v" değişkenine atar.
max_v = v.max()
# "max()" metodu, "v" dizisindeki en büyük elemanı bulur ve "max_v" değişkenine atar.
var_v = np.var(v)
# "np.var()" fonksiyonu, "v" dizisinin varyansını hesaplar ve "var_v" değişkenine atar.
std_v = np.std(v)
# "np.std()" fonksiyonu, "v" dizisinin standart sapmasını hesaplar ve "std_v" değişkenine atar.
corr_coef_v = np.corrcoef(v)
# "np.corrcoef()" fonksiyonu, "v" dizisinin korelasyon katsayısı matrisini hesaplar ve "corr_coef_v" değişkenine atar.
print(" mean_v: {} \n sum_v: {} \n min_v: {} \n max_v: {} \n var_v: {} \n std_v: {} \n corr_coef_v: {}".format(mean_v,sum_v,min_v,max_v,var_v,std_v,corr_coef_v))

 mean_v: 3.0 
 sum_v: 15 
 min_v: 1 
 max_v: 5 
 var_v: 2.0 
 std_v: 1.4142135623730951 
 corr_coef_v: 1.0
